#ifndef _ALTERA_ARM_A9_HPS_H_
#define _ALTERA_ARM_A9_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'Computer_System' in
 * file './Computer_System.sopcinfo'.
 */

/*
 * This file contains macros for module 'ARM_A9_HPS' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'fifo_HPS_to_FPGA_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_HPS_TO_FPGA_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_HPS_TO_FPGA_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_HPS_TO_FPGA_IN_COMPONENT_NAME fifo_HPS_to_FPGA
#define FIFO_HPS_TO_FPGA_IN_BASE 0x0
#define FIFO_HPS_TO_FPGA_IN_SPAN 4
#define FIFO_HPS_TO_FPGA_IN_END 0x3
#define FIFO_HPS_TO_FPGA_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_HPS_TO_FPGA_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_HPS_TO_FPGA_IN_BITS_PER_SYMBOL 16
#define FIFO_HPS_TO_FPGA_IN_CHANNEL_WIDTH 8
#define FIFO_HPS_TO_FPGA_IN_ERROR_WIDTH 8
#define FIFO_HPS_TO_FPGA_IN_FIFO_DEPTH 256
#define FIFO_HPS_TO_FPGA_IN_SINGLE_CLOCK_MODE 0
#define FIFO_HPS_TO_FPGA_IN_SYMBOLS_PER_BEAT 2
#define FIFO_HPS_TO_FPGA_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_HPS_TO_FPGA_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_HPS_TO_FPGA_IN_USE_AVALONST_SINK 0
#define FIFO_HPS_TO_FPGA_IN_USE_AVALONST_SOURCE 0
#define FIFO_HPS_TO_FPGA_IN_USE_BACKPRESSURE 1
#define FIFO_HPS_TO_FPGA_IN_USE_IRQ 0
#define FIFO_HPS_TO_FPGA_IN_USE_PACKET 1
#define FIFO_HPS_TO_FPGA_IN_USE_READ_CONTROL 1
#define FIFO_HPS_TO_FPGA_IN_USE_REGISTER 0
#define FIFO_HPS_TO_FPGA_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_HPS_to_FPGA_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_HPS_TO_FPGA_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_HPS_TO_FPGA_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_HPS_TO_FPGA_IN_CSR_COMPONENT_NAME fifo_HPS_to_FPGA
#define FIFO_HPS_TO_FPGA_IN_CSR_BASE 0x0
#define FIFO_HPS_TO_FPGA_IN_CSR_SPAN 32
#define FIFO_HPS_TO_FPGA_IN_CSR_END 0x1f
#define FIFO_HPS_TO_FPGA_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_HPS_TO_FPGA_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_HPS_TO_FPGA_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_HPS_TO_FPGA_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_HPS_TO_FPGA_IN_CSR_ERROR_WIDTH 8
#define FIFO_HPS_TO_FPGA_IN_CSR_FIFO_DEPTH 256
#define FIFO_HPS_TO_FPGA_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_HPS_TO_FPGA_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_HPS_TO_FPGA_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_HPS_TO_FPGA_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_HPS_TO_FPGA_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_HPS_TO_FPGA_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_HPS_TO_FPGA_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_HPS_TO_FPGA_IN_CSR_USE_IRQ 0
#define FIFO_HPS_TO_FPGA_IN_CSR_USE_PACKET 1
#define FIFO_HPS_TO_FPGA_IN_CSR_USE_READ_CONTROL 1
#define FIFO_HPS_TO_FPGA_IN_CSR_USE_REGISTER 0
#define FIFO_HPS_TO_FPGA_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'Onchip_SRAM', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_SRAM_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_SRAM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_SRAM_COMPONENT_NAME Onchip_SRAM
#define ONCHIP_SRAM_BASE 0x8000000
#define ONCHIP_SRAM_SPAN 1024
#define ONCHIP_SRAM_END 0x80003ff
#define ONCHIP_SRAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_SRAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_SRAM_CONTENTS_INFO ""
#define ONCHIP_SRAM_DUAL_PORT 1
#define ONCHIP_SRAM_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_SRAM_INIT_CONTENTS_FILE Computer_System_Onchip_SRAM
#define ONCHIP_SRAM_INIT_MEM_CONTENT 0
#define ONCHIP_SRAM_INSTANCE_ID NONE
#define ONCHIP_SRAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_SRAM_RAM_BLOCK_TYPE AUTO
#define ONCHIP_SRAM_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_SRAM_SINGLE_CLOCK_OP 0
#define ONCHIP_SRAM_SIZE_MULTIPLE 1
#define ONCHIP_SRAM_SIZE_VALUE 1024
#define ONCHIP_SRAM_WRITABLE 1
#define ONCHIP_SRAM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_SRAM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_SRAM_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_SRAM_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_SRAM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_SRAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define ONCHIP_SRAM_MEMORY_INFO_MEM_INIT_FILENAME Computer_System_Onchip_SRAM


#endif /* _ALTERA_ARM_A9_HPS_H_ */
